language: c
os: osx
sudo: true
env:
    global:
        - CODECOV_TOKEN="4238da1d-a3de-4d6e-8840-1fa2db5b1572"
        - HOMEBREW_NO_AUTO_UPDATE=1
branches:
    only:
        - master
install:
    - brew install snaipe/soft/criterion
    - git clone --depth=1 https://github.com/thijsdejong/codam-norminette-plus ~/norminette+
    - sudo mkdir -p /Volumes/Storage/goinfre
    - sudo touch /Volumes/Storage/goinfre/filewithoutuser
    - sudo touch /Volumes/Storage/goinfre/filewithoutgroup
    - sudo touch /Volumes/Storage/goinfre/filewithoutuserandgroup
    - sudo mkdir test_files/files_for_tests/nopermissions
    - sudo ln -s test_files/files_for_tests/link1 test_files/files_for_tests/link2
    - sudo ln -s test_files/files_for_tests/link2 test_files/files_for_tests/link1
    - sudo chmod 000 test_files/files_for_tests/nopermissions
    - sudo chown 4242 /Volumes/Storage/goinfre/filewithoutuser
    - sudo chown root:4242 /Volumes/Storage/goinfre/filewithoutgroup
    - sudo chown 4242:4343 /Volumes/Storage/goinfre/filewithoutuserandgroup
    - ls -la /Volumes/Storage/goinfre
before_script:
    - make test COV=1
script:
    - ./test
    - ./end2endls.sh
after_success:
    - make gcov
    - bash <(curl -s https://codecov.io/bash) -X gcov
after_failure:
    - cat testresults.txt
