language: c
os: osx
sudo: true
env:
    global:
        - CODECOV_TOKEN="4238da1d-a3de-4d6e-8840-1fa2db5b1572"
        - HOMEBREW_NO_AUTO_UPDATE=1
branches:
    only:
        - master
install:
    - brew install snaipe/soft/criterion
    - git clone --depth=1 https://github.com/thijsdejong/codam-norminette-plus ~/norminette+
before_script:
    - make test COV=1
script:
    - ./test
    - ./end2endls.sh
after_success:
    - make gcov
    - bash <(curl -s https://codecov.io/bash) -X gcov
after_failure:
    - cat testresults.txt
